Initial implementation
famous-warplane/clamav-processor pull request #1
Opened 2022-04-04 15:06 UTC by JonathanGeorgiou

2022-04-04 15:10 UTC, djaustin requested changes
Rename this file to main.go please as that seems to be convention for runnable modules like this.

You'll also want to turn this into a module, there is some weird 'global go' thing that was used in the past but now people use modules to segregate projects so things don't get messy with dependencies. To do this, you run `go mod init <repo url>` i.e. `go mod init github.com/famous-warplane/clamav-processor`. That will allow this code to be built and is generally the first thing I do when creating a new Go project as things can get messy otherwise. :)

2022-04-04 15:25 UTC, annabelkimber commented on clamav.go
> +	scanResultsArray := runClamdscan("/tmp/input/*", "/tmp/virus")
Is it worth having the file locations as environment variables so it's more vague?

2022-04-04 15:32 UTC, djaustin requested changes

2022-04-04 15:32 UTC, djaustin commented on clamav.go
> +	scanResultsArray := runClamdscan("/tmp/input/*", "/tmp/virus")
We need to make sure these are configurable. Options we have are: 
* Command line arguments
* Command line flags
* Environment variables
* Config file

You can choose :) 

You can get the first three from the standard library using things like [os.Args](https://pkg.go.dev/os#Args), the [flag package](https://pkg.go.dev/flag), [os.Getenv](https://pkg.go.dev/os#Getenv)

[Viper](https://pkg.go.dev/github.com/spf13/viper) is a package used by lots of CLI tools for managing configuration and includes a nice interface to cover all the above in one but it'll take a little learning and may just not be needed here.

2022-04-04 15:32 UTC, djaustin commented on clamav.go
> +			filePath := s.Split(line, ":")[0]
I think we should check whether there actually is an element in this slice just in case ClamAV does something funky to prevent the application from panicking 
```suggestion
			parts := s.Split(line, ":")
			if len(parts) < 1 {
			    log.Printf("failed to parse output line %q: line does not contain expected character ':'", s)
			    continue
			}
			filePath := parts[0]
```

2022-04-04 15:32 UTC, djaustin commented on clamav.go
> +			mvCmd := exec.Command("/bin/sh", "-c", "mv "+filePath+" /tmp/goodfiles")
It's probably better to use [os.Rename](https://pkg.go.dev/os#Rename) here so you get all the support of the language with more useful errors etc. I'd also have a check to make sure that the destination path exists. Though this is probably best done at the start of the execution of this program rather than once each iteration :)

2022-04-04 15:32 UTC, djaustin commented on clamav.go
> +	return outputArray
Yes I'm being petty but hey this is good stuff in general so I have to find the quirks 👀 

Adding the type of the variable to the name is unnecessary in the vast majority of situations and just makes for longer names!

That aside, you can just return the result of split without assigning as well 
```suggestion
	return s.Split(string(stdout), "\n")
```

2022-04-04 15:33 UTC, djaustin commented
Really good work @JonathanGeorgiou for picking this up so quickly and integrating with another tool!

2022-04-04 16:27 UTC, djaustin commented on clamav.go
> +	scanResultsArray := runClamdscan("/tmp/input/*", "/tmp/virus")
The shaaaaade

2022-04-07 14:25 UTC, annabelkimber approved these changes

2022-04-07 14:46 UTC, djaustin approved these changes

2022-04-07 14:46 UTC, merged